name: redux_saga
maintainer: Bilal Uslu (@bilaluslu)
description: redux_saga is a library that aims to make application side effects easier to manage, more efficient to execute, easy to test, and better at handling failures.
homepage: https://github.com/reduxsaga/redux_saga
version: 3.1.0
repository: https://github.com/reduxsaga/redux_saga

environment:
  sdk: '>=2.12.0 <=3.7.2'

dependencies:
  redux: ^5.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  fake_async: ^1.2.0
  lints: ^1.0.1
